-- ============================================================================
-- IMA Accelerator V1 — Staging Seed Data
-- ============================================================================
-- Purpose: Populate staging Supabase project with 5,000 students, 10 coaches,
--          1 owner, ~500k daily_reports, ~150k work_sessions, ~50k roadmap_progress
--          rows for Phase 24 load testing.
--
-- Usage:   Run against the staging project ONLY — NOT production:
--            npx supabase db execute --sql-file load-tests/seed/00001_staging_seed.sql
--          Or via the Supabase SQL editor in the staging dashboard.
--
-- WARNING: This script TRUNCATES all 6 main tables before inserting.
--          Running against production WILL DESTROY all real data.
--
-- Auth_id strategy (deterministic UUIDs — no auth.users rows needed):
--   Owner:     00000000-0000-4000-b000-000000000001
--   Coach N:   00000000-0000-4000-b000-{N+1 zero-padded to 12 digits}
--              e.g. coach 1  -> 00000000-0000-4000-b000-000000000002
--                   coach 10 -> 00000000-0000-4000-b000-000000000011
--   Student N: 00000000-0000-4000-a000-{N zero-padded to 12 digits}
--              e.g. student 1    -> 00000000-0000-4000-a000-000000000001
--                   student 5000 -> 00000000-0000-4000-a000-000000005000
--
-- These deterministic auth_ids match the JWT sub claims generated by
-- load-tests/scripts/gen-tokens.js.
--
-- Performance: All inserts are set-based (generate_series). Do NOT use
--              PL/pgSQL FOR LOOP over large row counts — that approach times
--              out at ~10k rows in the Supabase SQL editor. This script
--              completes in under 5 minutes for 500k+ rows.
-- ============================================================================

BEGIN;

-- ============================================================================
-- SAFETY GUARD: Abort if any real student rows exist (safety check)
-- Staging only: real production users have auth_ids that are NOT in the
-- deterministic 00000000-0000-4000-* prefix range.
-- ============================================================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM public.users
    WHERE auth_id IS NOT NULL
      AND auth_id::text NOT LIKE '00000000-0000-4000-%'
    LIMIT 1
  ) THEN
    RAISE EXCEPTION 'ABORT: Non-seed users detected. This script is for staging only. Refusing to truncate production data.';
  END IF;
END;
$$;

-- ============================================================================
-- STEP 0: Truncate tables in dependency order (cascade not needed — explicit)
-- ============================================================================
TRUNCATE TABLE public.daily_reports CASCADE;
TRUNCATE TABLE public.work_sessions CASCADE;
TRUNCATE TABLE public.roadmap_progress CASCADE;
TRUNCATE TABLE public.users CASCADE;

-- ============================================================================
-- STEP 1: Create owner user
-- auth_id: 00000000-0000-4000-b000-000000000001
-- ============================================================================
INSERT INTO public.users (
  id,
  auth_id,
  email,
  name,
  role,
  status,
  joined_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  '00000000-0000-4000-b000-000000000001'::uuid,
  'owner@test.ima',
  'Test Owner',
  'owner',
  'active',
  now() - interval '180 days',
  now() - interval '180 days',
  now();

-- ============================================================================
-- STEP 2: Create 10 coach users
-- auth_id pattern: 00000000-0000-4000-b000-{N+1 zero-padded to 12 digits}
-- e.g. coach 1 -> 000000000002, coach 10 -> 000000000011
-- ============================================================================
INSERT INTO public.users (
  id,
  auth_id,
  email,
  name,
  role,
  status,
  joined_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  ('00000000-0000-4000-b000-' || lpad((n + 1)::text, 12, '0'))::uuid,
  'coach' || n || '@test.ima',
  'Test Coach ' || n,
  'coach',
  'active',
  now() - interval '150 days',
  now() - interval '150 days',
  now()
FROM generate_series(1, 10) AS n;

-- ============================================================================
-- STEP 3: Create 5,000 student users
-- auth_id pattern: 00000000-0000-4000-a000-{N zero-padded to 12 digits}
-- Coach assignment: round-robin across coaches 1-10
-- ============================================================================

-- Capture coach UUIDs for coach_id assignment
CREATE TEMP TABLE _seed_coaches AS
SELECT
  id,
  ROW_NUMBER() OVER (ORDER BY email) AS coach_num
FROM public.users
WHERE role = 'coach';

INSERT INTO public.users (
  id,
  auth_id,
  email,
  name,
  role,
  coach_id,
  niche,
  status,
  joined_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  ('00000000-0000-4000-a000-' || lpad(n::text, 12, '0'))::uuid,
  'student' || n || '@test.ima',
  'Test Student ' || n,
  'student',
  (SELECT id FROM _seed_coaches WHERE coach_num = (((n - 1) % 10) + 1)),
  CASE (n % 5)
    WHEN 0 THEN 'Fashion'
    WHEN 1 THEN 'Fitness'
    WHEN 2 THEN 'Food'
    WHEN 3 THEN 'Tech'
    ELSE 'Lifestyle'
  END,
  'active',
  now() - interval '90 days',
  now() - interval '90 days',
  now()
FROM generate_series(1, 5000) AS n;

-- Capture student UUIDs for subsequent inserts
CREATE TEMP TABLE _seed_students AS
SELECT
  id AS student_id,
  ROW_NUMBER() OVER (ORDER BY email) AS student_num
FROM public.users
WHERE role = 'student';

-- ============================================================================
-- STEP 4: Create ~90 daily_reports per student (~500k rows total)
-- Date range: 89 days ago to yesterday (90 days)
-- Hours: random 2.0-8.0
-- Star rating: random 1-5
-- Outreach counts: random distributions
-- submitted_at spike: 80% of timestamps in 9-11 PM UTC window (D-07)
-- ============================================================================
INSERT INTO public.daily_reports (
  id,
  student_id,
  date,
  hours_worked,
  star_rating,
  outreach_count,
  brands_contacted,
  influencers_contacted,
  calls_joined,
  wins,
  improvements,
  submitted_at,
  created_at
)
SELECT
  gen_random_uuid(),
  s.student_id,
  (CURRENT_DATE - d.days_ago)::date                          AS date,
  -- hours_worked: random 2.0 to 8.0 in 0.5 increments
  (2.0 + (floor(random() * 13) * 0.5))::decimal(4,2)        AS hours_worked,
  -- star_rating: random 1-5
  (1 + floor(random() * 5))::int                             AS star_rating,
  -- outreach_count: 0-15
  floor(random() * 16)::int                                  AS outreach_count,
  -- brands_contacted: 0-10
  floor(random() * 11)::int                                  AS brands_contacted,
  -- influencers_contacted: 0-5
  floor(random() * 6)::int                                   AS influencers_contacted,
  -- calls_joined: 0-3
  floor(random() * 4)::int                                   AS calls_joined,
  'Great progress on day ' || (90 - d.days_ago)             AS wins,
  'Could improve focus tomorrow'                             AS improvements,
  -- submitted_at spike distribution (D-07):
  -- 80% of reports submitted 21-22 UTC (9-11 PM), 20% random 0-20 UTC
  CASE
    WHEN random() < 0.8
      THEN ((CURRENT_DATE - d.days_ago)::date
            + make_interval(hours => 21 + floor(random() * 2)::int,
                           mins  => floor(random() * 60)::int))::timestamptz
    ELSE
          ((CURRENT_DATE - d.days_ago)::date
            + make_interval(hours => floor(random() * 21)::int,
                           mins  => floor(random() * 60)::int))::timestamptz
  END                                                        AS submitted_at,
  now() - make_interval(days => d.days_ago)                  AS created_at
FROM _seed_students s
CROSS JOIN generate_series(1, 89) AS d(days_ago);

-- ============================================================================
-- STEP 5: Create ~2-3 work_sessions per student per day for first 30 days
-- (~150k-450k rows total, keeping volume reasonable)
-- session_minutes: randomly 30, 45, or 60 (added in migration 00006)
-- ============================================================================
INSERT INTO public.work_sessions (
  id,
  student_id,
  date,
  cycle_number,
  session_minutes,
  started_at,
  completed_at,
  duration_minutes,
  status,
  created_at
)
SELECT
  gen_random_uuid(),
  s.student_id,
  (CURRENT_DATE - d.days_ago)::date                          AS date,
  c.cycle_number,
  -- session_minutes: 30, 45, or 60
  CASE floor(random() * 3)::int
    WHEN 0 THEN 30
    WHEN 1 THEN 45
    ELSE 60
  END                                                        AS session_minutes,
  -- started_at: random hour 7-21 UTC + cycle offset
  ((CURRENT_DATE - d.days_ago)::date
    + make_interval(hours => 7 + floor(random() * 14)::int + (c.cycle_number - 1) * 1,
                   mins  => floor(random() * 60)::int))::timestamptz AS started_at,
  -- completed_at = started_at + session_minutes
  ((CURRENT_DATE - d.days_ago)::date
    + make_interval(hours => 7 + floor(random() * 14)::int + (c.cycle_number - 1) * 1,
                   mins  => floor(random() * 60)::int,
                   secs  => CASE floor(random() * 3)::int
                               WHEN 0 THEN 30 * 60
                               WHEN 1 THEN 45 * 60
                               ELSE 60 * 60
                             END))::timestamptz              AS completed_at,
  -- duration_minutes: same as session_minutes
  CASE floor(random() * 3)::int
    WHEN 0 THEN 30
    WHEN 1 THEN 45
    ELSE 60
  END                                                        AS duration_minutes,
  'completed'                                                AS status,
  now() - make_interval(days => d.days_ago)                  AS created_at
FROM _seed_students s
CROSS JOIN generate_series(1, 29) AS d(days_ago)
CROSS JOIN (VALUES (1), (2), (3)) AS c(cycle_number);

-- ============================================================================
-- STEP 6: Create 10 roadmap_progress rows per student (~50k rows total)
-- Steps 1-3: completed, step 4: active, steps 5-10: locked
-- ============================================================================
INSERT INTO public.roadmap_progress (
  id,
  student_id,
  step_number,
  step_name,
  status,
  completed_at,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  s.student_id,
  r.step_number,
  r.step_name,
  CASE
    WHEN r.step_number <= 3 THEN 'completed'
    WHEN r.step_number = 4  THEN 'active'
    ELSE                        'locked'
  END AS status,
  CASE
    WHEN r.step_number <= 3
      THEN now() - make_interval(days => 90 - (r.step_number * 15))
    ELSE NULL
  END AS completed_at,
  now() - interval '90 days',
  now()
FROM _seed_students s
CROSS JOIN (VALUES
  (1,  'Join Course'),
  (2,  'Watch Intro'),
  (3,  'Set Up IG'),
  (4,  'First DM'),
  (5,  'Book Call'),
  (6,  'Sign Client'),
  (7,  'First Invoice'),
  (8,  'Testimonial'),
  (9,  'Scale Up'),
  (10, 'Brand Deal')
) AS r(step_number, step_name);

-- ============================================================================
-- STEP 7: Clean up temp tables
-- ============================================================================
DROP TABLE _seed_coaches;
DROP TABLE _seed_students;

-- ============================================================================
-- STEP 8: Verify counts (printed as result set after commit)
-- ============================================================================
COMMIT;

-- Post-commit verification queries
SELECT
  'users' AS table_name,
  COUNT(*) AS row_count,
  COUNT(*) FILTER (WHERE role = 'owner')   AS owner_count,
  COUNT(*) FILTER (WHERE role = 'coach')   AS coach_count,
  COUNT(*) FILTER (WHERE role = 'student') AS student_count
FROM public.users;

SELECT
  'daily_reports' AS table_name,
  COUNT(*) AS row_count,
  COUNT(*) FILTER (WHERE date_part('hour', submitted_at) BETWEEN 21 AND 22) AS spike_window_count,
  ROUND(COUNT(*) FILTER (WHERE date_part('hour', submitted_at) BETWEEN 21 AND 22) * 100.0 / COUNT(*), 1) AS spike_pct
FROM public.daily_reports;

SELECT 'work_sessions' AS table_name, COUNT(*) AS row_count FROM public.work_sessions;
SELECT 'roadmap_progress' AS table_name, COUNT(*) AS row_count FROM public.roadmap_progress;
